### ISSUE TITLE
'npm test' failed with an error

### ISSUE THREAD

**Issue by jefffranks** [wbkd/react-starterkit#2]
Hi,

I did a git clone and followed the README.md.
'npm install' is okay.
'gulp' is okay.
'gulp build --type production' is okay
'npm test' produced an error for me (see below).

Is there something that I did not do to make this work correctly?
Please let me know.

-- Regards: Jeff Franks

---- console session showing the error ----
jfranks@jlf-mint-17 ~/Desktop/ws1 - reflux-getting-started/react-starterkit $ npm test

> webkid-react-starterkit@0.3.1 test /home/jfranks/Desktop/ws1 - reflux-getting-started/react-starterkit
> jest

Using Jest CLI v0.4.5
 FAIL  app/scripts/__tests__/itemlist-test.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:

A worker process has quit unexpectedly! This is bad news, shutting down now!
npm ERR! Test failed.  See above for more details.
------------------------

**Comment by moklick** [comment]
Thanks @jefffranks! I will check that. The steps you did are correct..

**Comment by moklick** [comment]
It's working on my machine, but I saw that there is an open issue regarding this error: https://github.com/facebook/jest/issues/243

Maybe it's because of the Node version you are using.

**Comment by jefffranks** [comment]
Hi moklick,

Yes, you are right,

I down-graded my node version from v0.12.2 --> v0.10.33.
npm is now at v2.11.1
Also, had to remove all npm cache scratch everything related to node v0.12.2 for the un-install.
Using these versions, I was able to obtain a good result.

The following console log shows the good results
======= console log ================
jfranks@jlf-mint-17 ~/Desktop/ws1 - reflux-getting-started/react-starterkit $ npm test

> webkid-react-starterkit@0.3.1 test /home/jfranks/Desktop/ws1 - reflux-getting-started/react-starterkit
> jest

Using Jest CLI v0.4.5
 PASS  app/scripts/__tests__/itemlist-test.js (1.922s)
 PASS  app/scripts/__tests__/header-test.js (2.253s)
2 tests passed (2 total)
Run time: 3.861s
=======

**Comment by moklick** [comment]
ok. nice to hear that.. So I think we have to keep an eye on the jest issue
